### PR TITLE
No country selected does not mean all selected

### PR DESCRIPTION
**Pull request by oxFilla**

### CODE REVIEW

**Comment by Sieg** [comment]
Hello @oxid-filla, i have just tested this on 6.2(there were no changes to this section from the 6.1 as i know): when i remove all countries from the payment method country list, that payment is available for me with my country. If i put some country that is not mine only, the payment is not available.

Could you please double check, and give more information about the conditions you are getting this outcome?

**Comment by Sieg** [comment]
Hello @oxid-filla, as there are no response from your side, and we cannot reproduce this locally, i am closing this for now. Please consider reopening if you have more information on how to reproduce it.

**Comment by oxFilla** [comment]
Sorry, forgot to answer. The problem was the demo data which resulted in that effect. There are countries (Switzerland, Austria) activated which cant be seen in the backend.

**Comment by Sieg** [comment]
Hey @oxid-filla, is it our demodata that causes issues? Could you point more precisely?

**Pull request closed without merging**
